### ISSUE TITLE
[Docs]Readme Enhancement

### ISSUE THREAD

**Issue by Anubhavdevv** [layer5io/meet#11]
**Current State:**
The meeting and Zoom Links in GitHub readme are in link format it is not looking good 

**Desired State:**
It will be Great if Readme has a hyperlink embedded in a markdown file rather than posting simple websites link

**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by anubhav201241** [comment]
@warunicorn19
plz assign this issue to me
