### ISSUE TITLE
Issue Template Updates for Figma link 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/meet#24]
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Layer5](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

**Acceptance Tests**
All references to Figma include the "open invite" link.

---
**Implementation**

**Mockups**

**Acceptance Tests**

**Comment by csengineer1990** [comment]
Please assign me if not a problem assign two issues to the newcomer. As already I am working on this issue https://github.com/layer5io/meshery-service-mesh-patterns-actionIssue Template Updates for Figma link.

**Comment by Sankhadip-Roy** [comment]
Can I work on this?

**Comment by Sankhadip-Roy** [comment]
Hello @thisiskaransgit , in the PR #25 I mistakenly pushed .vscode folder & then used git reset --hard HEAD~1 & the PR got closed accidentally. Sorry for the mistake.
So I have submitted a new PR #26 to this issue. Could you please review it and provide feedback? Thank you!

**Comment by abhijeetgauravm** [comment]
I want to work on it. Can u assign me?
