### ISSUE TITLE
to fix error in "Slack Notify on Star" Job under GitHub Actions 

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/meet#28]
## Description
Under **GitHub Actions** of this repository **"[Slack Notify on Star](https://github.com/layer5io/meet/actions/runs/6325356550)"** job is failing for which [Slack.yaml](https://github.com/layer5io/meet/blob/master/.github/workflows/slack.yml) is to be Updated.

## Fix
To fix this issue, update the code of [slack.yaml](https://github.com/layer5io/meet/blob/master/.github/workflows/slack.yml) just by copy/pasting the code from[ slack.yaml](https://github.com/meshery/meshery/blob/master/.github/workflows/slack.yml) of [meshery](https://github.com/meshery/meshery)

**Comment by jamieplu** [comment]
I would like to volunteer to fix this issue.
